In [2]:
pip install kmodes

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting kmodes
  Downloading kmodes-0.12.2-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from kmodes) (1.2.0)
Requirement already satisfied: scipy>=0.13.3 in /usr/local/lib/python3.7/dist-packages (from kmodes) (1.7.3)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.7/dist-packages (from kmodes) (1.21.6)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.7/dist-packages (from kmodes) (1.0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.22.0->kmodes) (3.1.0)
Installing collected packages: kmodes
Successfully installed kmodes-0.12.2

In [3]:
import pandas as pd
import numpy as np
from kmodes.kmodes import KModes
from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_csv('/content/kmodes.csv')
df.head()

  Person hair color eye color skin color
0     p1     blonde     amber       fair
1     p2   brunette      gray      brown
2     p3        red     green      brown
3     p4      black     hazel      brown
4     p5   brunette     amber       fair

In [12]:
kmode = KModes(n_clusters=3)
clusters = kmode.fit_predict(df)

In [13]:
print(clusters)

[1 2 0 0 1 0 1 0]

In [14]:
df['cluster'] = clusters
df

  Person hair color eye color skin color  cluster
0     p1     blonde     amber       fair        1
1     p2   brunette      gray      brown        2
2     p3        red     green      brown        0
3     p4      black     hazel      brown        0
4     p5   brunette     amber       fair        1
5     p6      black      gray      brown        0
6     p7        red     green       fair        1
7     p8      black     hazel       fair        0